// <auto-generated />
using Facebook_MKT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Facebook_MKT.Data.Migrations
{
    [DbContext(typeof(FBDataContext))]
    [Migration("20240812165704_seedingdatafolder")]
    partial class seedingdatafolder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Facebook_MKT.Data.Entities.Account", b =>
                {
                    b.Property<int>("AccountIDKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("C_2FA")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cookie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email1Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email2Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("FolderIdKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GPMID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Proxy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("UID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountIDKey");

                    b.HasIndex("FolderIdKey");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Facebook_MKT.Data.Entities.Folder", b =>
                {
                    b.Property<int>("FolderIdKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FolderIdKey");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            FolderIdKey = 1,
                            FolderName = "All"
                        });
                });

            modelBuilder.Entity("Facebook_MKT.Data.Entities.Page", b =>
                {
                    b.Property<int>("PageIdKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderIdKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageFollow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageLike")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PageIdKey");

                    b.HasIndex("AccountID");

                    b.HasIndex("FolderIdKey");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Facebook_MKT.Data.Entities.Account", b =>
                {
                    b.HasOne("Facebook_MKT.Data.Entities.Folder", "Folder")
                        .WithMany("Accounts")
                        .HasForeignKey("FolderIdKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Facebook_MKT.Data.Entities.Page", b =>
                {
                    b.HasOne("Facebook_MKT.Data.Entities.Account", "Account")
                        .WithMany("Pages")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Facebook_MKT.Data.Entities.Folder", "Folder")
                        .WithMany("Pages")
                        .HasForeignKey("FolderIdKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Facebook_MKT.Data.Entities.Account", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("Facebook_MKT.Data.Entities.Folder", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
